#!/bin/bash

filename=.shrug
if [ ! -d "$filename" ]
then
	mkdir $filename
	echo Initialized empty shrug repository in $filename
	mkdir $filename/.commit
	mkdir $filename/.index
else
	echo shrug-init: error: .shrug already exists
fi