#!/bin/bash
if [ ! -d ".shrug" ]
then
	echo Usage: shrug-init before shrug-log 
	exit 1
fi

number=`ls .shrug/.commit | wc -l`
number=$((number-1))
while [ $number -ge 0 ]
do
	message=`cat ".shrug/.commit/"$number"/.message.txt"`
	echo "$number" $message
	number=$((number-1))
done